### ISSUE TITLE
x-www-form-urlencoded content type not working

### ISSUE THREAD

**Issue by ttola** [HecJimSan/stub-backend#54]
**Describe the bug**
When adding an 'Content-Type' header field, the matcher fails to match the request body, and returns an error
```
{
    "errorCode": 404,
    "message": "Request body not found in the resources! :("
}
```

**To Reproduce**
1. Add a new header content type of `application/x-www-form-urlencoded`
2. Send a request with urlencoded content type
3. See error response

**Expected behavior**
Should return the matching response

**Comment by HecJimSan** [comment]
First of all, thanks for the contribution @ttola. 

Unfortunately, this issue is not supported at this moment in this library 🤦 .
I have created a feature and we will work on that. 
#55   

I will close this issue.

**Comment by HecJimSan** [comment]
https://github.com/HecJimSan/stub-cli/issues/36. Btw, I have opened another feature here 😄
