### ISSUE TITLE
Seperate express app create and listen 

### ISSUE THREAD

**Issue by ttola** [HecJimSan/stub-backend#57]
**Is your feature request related to a problem? Please describe.**
Seperate the instance for creating and app and listen. 

**Describe the solution you'd like**
Seperate modules for each action

**Comment by HecJimSan** [comment]
This feature will be part of this release 
https://github.com/HecJimSan/stub-backend/releases/tag/v1.3.0

It is already published
[1.3.0](https://www.npmjs.com/package/@hectorjs/stub-backend/v/1.3.0)

@ttola  thanks for the contribution 😄
